bald: false
data.canonical_flame_path: /apdcephfs_cq2/share_1467498/datasets/nersemble/preprocess/264/264_EMO-1_v16_DS2-0.5x_lmkSTAR_teethV3_SMOOTH_offsetS_whiteBg_maskBelowLine/flame_param/00000.npz
data.img_h: 802
data.img_w: 550
data.load_images: false
data.num_workers: 0
data.per_gpu_batch_size: 2
data.root: /apdcephfs_cq2/share_1467498/datasets/nersemble/preprocess/264/UNION10_264_EMO1234EXP234589_v16_DS2-0.5x_lmkSTAR_teethV3_SMOOTH_offsetS_whiteBg_maskBelowLine
flame.add_teeth: true
flame.enable_offsets: true
flame.ignore_faces: /apdcephfs_cq2/share_1467498/datasets/face-data/H3Avatar/flame/lower_neck_bottom_face_idcs.npy
flame.lmk_embedding_path: /apdcephfs_cq2/share_1467498/datasets/face-data/H3Avatar/flame2023/landmark_embedding_with_eyes.npy
flame.model_path: /apdcephfs_cq2/share_1467498/datasets/face-data/H3Avatar/flame2023/flame2023.pkl
flame.move_eyes: false
flame.n_expr: 100
flame.n_pose: 15
flame.n_shape: 300
flame.offsets_ignore_parts:
- null
flame.optimize_params: true
flame.parts_path: /apdcephfs_cq2/share_1467498/datasets/face-data/H3Avatar/flame/FLAME_masks_mouth.pkl
flame.subdivision: 1
flame.subdivision.mouth: 0
flame.xyz_cond: false
gs.K: 8
gs.deform_attr:
- xyz
- rotation
- scaling
- opacity
- features_dc
gs.deform_layers:
- 256
- 256
gs.deform_lr: 0.001
gs.deform_weightnorm: false
gs.densification_interval: 200
gs.densify_from_iter: 500
gs.densify_grad_threshold: 0.0002
gs.densify_until_iter: 15000
gs.enable_aiap: true
gs.enable_reset: false
gs.feature_lr: 0.0025
gs.init_pts: /apdcephfs_cq2/share_1467498/datasets/nersemble/preprocess/264/init_pts_150000.npy
gs.opacity_lr: 0.05
gs.opacity_reset_interval: 3000
gs.pe.num_freqs: 6
gs.percent_dense: 0.002
gs.position_lr_delay_mult: 0.01
gs.position_lr_final: 1.6e-06
gs.position_lr_init: 0.00016
gs.position_lr_max_steps: 30000
gs.pretrain: /apdcephfs/share_1467498/home/conallwang/checkpoints/DWG/0227/train_264_b8_DWG_neutral_hair/checkpoint_reset.pth
gs.rotation_lr: 0.001
gs.scaling_lr: 0.005
gs.sh_degree: 3
gs.split_inteval: 100
gs.split_rate_threshold: 2
gs.upSH: 1000
pipe.compute_cov3D_python: false
pipe.convert_SHs_python: false
pipe.debug: false
pipe.neutral_hair: false
training.depth_thres: 5
training.enable_densify: true
training.enc.mode: texture
training.epochs: 100
training.eval_interval: 5000
training.gpus: '0'
training.head_stage_loss:
- head
training.joint_stage_loss:
- hair
- general
training.lambda_aiap.cov: 100000.0
training.lambda_aiap.xyz: 1000.0
training.lambda_depth.head: 1.0
training.lambda_features_dc: 10.0
training.lambda_lpips: 0.0
training.lambda_mesh.edges: 100.0
training.lambda_mesh.laplacian: 50.0
training.lambda_mesh.normal: 0.1
training.lambda_mesh.verts_scale: 1.0
training.lambda_normal.head: 2.0
training.lambda_opacity: 10.0
training.lambda_rgb: 1.0
training.lambda_rgb.hair: 1.0
training.lambda_rgb.head: 1.0
training.lambda_rotation: 10.0
training.lambda_scaling: 10.0
training.lambda_silh.hair: 0.2
training.lambda_silh.solid_hair: 0.1
training.lambda_ssim: 0.2
training.lambda_update_list:
- null
training.learning_rate: 0.001
training.neural_texture: false
training.pe: LPE
training.pe.include_input: true
training.pe.log_sampling: true
training.pe.num_freqs: 8
training.pretrained_checkpoint_path: null
training.stages:
- head
- joint
training.stages_epoch:
- 50
training.step:
- null
training.tex_ch: 4
training.tex_size: 1024
training.visual_interval: 200
